version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dispenser_db
    networks:
      - ddback-net
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /dispenser
    networks:
      - ddback-net
  drinks-dispenser-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drinks-dispenser-backend
    ports:
      - "8088:8088"
    networks:
      - ddback-net
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/dispenser_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
networks:
  ddback-net:
    name: ddback-net





